#!/bin/sh

# bspwm configuration

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

# Start sxhkd
sxhkd &
